# Generated by Django 4.2.30 on 2026-05-16 22:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomSpecRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('material', models.CharField(max_length=50, verbose_name='材料')),
                ('process_type', models.CharField(max_length=50, verbose_name='加工方式')),
                ('thickness', models.CharField(max_length=20, verbose_name='厚度')),
                ('description', models.TextField(blank=True, verbose_name='申请说明')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='审核状态')),
                ('review_note', models.TextField(blank=True, verbose_name='审核备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_spec_requests', to='accounts.merchant', verbose_name='申请商家')),
                ('reviewed_by', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'platform_admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_specs', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
            ],
            options={
                'verbose_name': '非标规格申请',
                'verbose_name_plural': '非标规格申请',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductSpec',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('material', models.CharField(choices=[('magnesium', '镁板'), ('copper', '铜板')], max_length=20, verbose_name='材料')),
                ('process_type', models.CharField(choices=[('etching', '腐蚀版'), ('engraving', '雕刻版'), ('resin', '树脂版'), ('film', '菲林')], max_length=20, verbose_name='加工方式')),
                ('thickness', models.CharField(choices=[('1.5', '1.5mm'), ('2.0', '2.0mm'), ('3.0', '3.0mm'), ('4.0', '4.0mm'), ('6.0', '6.0mm')], max_length=10, verbose_name='厚度')),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='平台基准单价(元/cm²)')),
                ('description', models.TextField(blank=True, verbose_name='规格说明')),
                ('is_platform_preset', models.BooleanField(default=True, verbose_name='是否平台预设')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否上架')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('merchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_specs', to='accounts.merchant', verbose_name='所属商家')),
            ],
            options={
                'verbose_name': '商品规格',
                'verbose_name_plural': '商品规格',
                'unique_together': {('material', 'process_type', 'thickness', 'merchant')},
            },
        ),
    ]
