# Generated by Django 4.2.30 on 2026-05-17 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customerprofile_pricing_tier_and_more'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productspec',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='productspec',
            name='product_name',
            field=models.CharField(choices=[('pingdiao', '平雕版'), ('fudiao', '浮雕烫凸一体/浮雕击凸'), ('duoceng', '多层次浮雕烫凸/击凸'), ('qita', '其他')], default='pingdiao', max_length=50, verbose_name='产品名称'),
        ),
        migrations.AddField(
            model_name='productspec',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='单价(元/cm²)'),
        ),
        migrations.AlterField(
            model_name='productspec',
            name='material',
            field=models.CharField(choices=[('magnesium', '镁'), ('copper', '铜'), ('resin', '树脂'), ('film', '菲林')], max_length=20, verbose_name='材质'),
        ),
        migrations.AlterField(
            model_name='productspec',
            name='thickness',
            field=models.CharField(choices=[('2.0', '2.0mm'), ('3.0', '3.0mm'), ('4.0', '4.0mm'), ('6.0', '6.0mm'), ('6.35', '6.35mm'), ('-', '不适用')], max_length=10, verbose_name='厚度'),
        ),
        migrations.AlterUniqueTogether(
            name='productspec',
            unique_together={('product_name', 'material', 'thickness', 'merchant')},
        ),
        migrations.RemoveField(
            model_name='productspec',
            name='base_price',
        ),
        migrations.RemoveField(
            model_name='productspec',
            name='process_type',
        ),
    ]
