# Generated by Django 4.2.30 on 2026-05-17 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_productspec_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productspec',
            name='product_name',
            field=models.CharField(choices=[('pingdiao', '平雕版'), ('fudiao', '浮雕烫凸一体/浮雕击凸'), ('duoceng', '多层次浮雕烫凸/击凸'), ('shike', '蚀刻镁板'), ('qita', '其他')], default='pingdiao', max_length=50, verbose_name='产品名称'),
        ),
        migrations.AlterField(
            model_name='productspec',
            name='thickness',
            field=models.CharField(choices=[('1.5', '1.5mm'), ('2.0', '2.0mm'), ('3.0', '3.0mm'), ('4.0', '4.0mm'), ('6.0', '6.0mm'), ('6.35', '6.35mm'), ('-', '不适用')], max_length=10, verbose_name='厚度'),
        ),
    ]
