# Generated by Django 4.2.30 on 2026-05-17 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productspec_product_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productspec',
            name='product_name',
            field=models.CharField(choices=[('shike', '蚀刻镁板'), ('pingdiao', '平雕版'), ('fudiao', '浮雕烫凸一体/浮雕击凸'), ('duoceng', '多层次浮雕烫凸/击凸'), ('qita', '其他')], default='pingdiao', max_length=50, verbose_name='产品名称'),
        ),
    ]
