# Generated by Django 4.2.30 on 2026-05-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_productspec_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productspec',
            name='material',
            field=models.CharField(choices=[('magnesium', '镁'), ('copper', '铜'), ('zinc', '锌'), ('stainless_steel', '不锈钢'), ('resin', '树脂'), ('film', '菲林')], max_length=20, verbose_name='材质'),
        ),
        migrations.AlterField(
            model_name='productspec',
            name='product_name',
            field=models.CharField(choices=[('etching_concave', '蚀刻凹版'), ('etching_convex', '蚀刻凸版/烫金版'), ('etching_bump_set', '蚀刻击凸/凹版'), ('carving_flat_gold', '平雕版-烫金版'), ('carving_flat_bump', '平雕版-击凸版'), ('carving_relief_gold_bump', '浮雕版-烫金击凸版'), ('carving_relief_bump_set', '浮雕版-浮雕击凸/凹版'), ('resin_mold', '倒模树脂版'), ('resin_water', '水洗树脂版'), ('film_alignment', '对位菲林'), ('film_uv', 'UV菲林')], default='etching_convex', max_length=50, verbose_name='产品名称'),
        ),
    ]
