# Generated by Django 4.2.30 on 2026-05-20 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_productspec_material_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productspec',
            name='product_name',
            field=models.CharField(choices=[('etching_concave', '腐蚀版 - 蚀刻凹版（压纹）'), ('etching_convex', '腐蚀版 - 蚀刻凸版（烫金/压凹）'), ('etching_bump_set', '腐蚀版 - 蚀刻击凸/凹版（配套）'), ('carving_flat_gold', '雕刻版 - 平雕版（烫金版）'), ('carving_flat_bump', '雕刻版 - 平雕版（击凸版）'), ('carving_relief_gold_bump', '雕刻版 - 浮雕版（烫金击凸版/烫凸一体）'), ('carving_relief_bump_set', '雕刻版 - 浮雕版（浮雕击凸/凹版）'), ('resin_mold', '树脂版 - 倒模树脂版'), ('resin_water', '树脂版 - 水洗树脂版'), ('film_alignment', '菲林 - 对位菲林'), ('film_uv', '菲林 - UV菲林')], default='etching_convex', max_length=50, verbose_name='产品名称'),
        ),
    ]
