# Generated by Django 4.2.30 on 2026-06-06 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_productspec_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productspec',
            name='product_name',
            field=models.CharField(choices=[('etching_concave', '腐蚀版 - 凹版'), ('etching_convex', '腐蚀版 - 凸版'), ('etching_magnesium_concave_resin_convex', '腐蚀版 - 镁凹树凸'), ('etching_double_sided_magnesium_bump', '腐蚀版 - 双面镁激凸'), ('carving_flat_convex', '雕刻版 - 平雕（凸版）'), ('carving_flat_concave', '雕刻版 - 平雕（凹版）'), ('carving_relief_bump_gold', '雕刻版 - 浮雕（激凸/烫凸一体）'), ('carving_relief_multi_bump_gold', '雕刻版 - 浮雕（多层次激凸/烫凸一体）'), ('carving_relief_complex', '雕刻版 - 多层复杂浮雕'), ('resin_mold', '树脂版 - 倒模树脂版'), ('resin_water', '树脂版 - 水洗树脂版'), ('film_alignment', '菲林 - 对位菲林'), ('film_uv', '菲林 - UV菲林')], default='etching_convex', max_length=50, verbose_name='产品名称'),
        ),
    ]
