# Generated by Django 4.2.30 on 2026-05-16 22:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('merchant_platform', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sn', models.CharField(blank=True, max_length=30, unique=True, verbose_name='订单编号')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending_confirm', '待确认'), ('design_confirmed', '设计确认并确认报价'), ('pending_payment', '待支付'), ('paid', '已支付'), ('in_production', '生产中'), ('shipped', '已发货'), ('received', '已收货'), ('info_error', '订单信息错误'), ('cancelled', '已取消')], default='draft', max_length=30, verbose_name='订单状态')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='订单总金额')),
                ('urgent', models.BooleanField(default=False, verbose_name='是否加急')),
                ('delivery_type', models.CharField(blank=True, choices=[('express', '快递'), ('flash', '闪送')], max_length=20, verbose_name='配送方式')),
                ('special_requests', models.TextField(blank=True, verbose_name='特殊要求备注')),
                ('preset_options', models.TextField(blank=True, default='', verbose_name='预定义选项')),
                ('production_cycle', models.PositiveIntegerField(blank=True, null=True, verbose_name='生产周期(小时)')),
                ('delivery_date', models.DateTimeField(blank=True, null=True, verbose_name='预计交货时间')),
                ('tracking_number', models.CharField(blank=True, max_length=100, verbose_name='物流单号')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='驳回/拒绝原因')),
                ('is_submitted', models.BooleanField(default=False, verbose_name='是否已提交')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='提交时间')),
                ('customer', models.ForeignKey(limit_choices_to={'user_type': 'customer'}, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='客户')),
                ('delivery_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.address', verbose_name='配送地址')),
                ('design_assigned_to', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'merchant_staff'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='design_orders', to=settings.AUTH_USER_MODEL, verbose_name='分配的设计人员')),
                ('factory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='merchant_platform.factory', verbose_name='生产工厂')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='accounts.merchant', verbose_name='所属商家')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductionPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('photo_type', models.CharField(choices=[('front', '成品正面'), ('inspection', '检测结果')], max_length=20, verbose_name='照片类型')),
                ('image', models.ImageField(upload_to='production_photos/%Y%m/', verbose_name='图片')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_photos', to='orders.order', verbose_name='所属订单')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='上传人')),
            ],
            options={
                'verbose_name': '生产照片',
                'verbose_name_plural': '生产照片',
            },
        ),
        migrations.CreateModel(
            name='PlateLayout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('layout_data', models.TextField(blank=True, default='', verbose_name='拼版布局数据')),
                ('layout_file', models.FileField(blank=True, null=True, upload_to='plate_layouts/%Y%m/', verbose_name='拼版文件')),
                ('material_usage_rate', models.FloatField(blank=True, null=True, verbose_name='材料利用率(%)')),
                ('designer_note', models.TextField(blank=True, verbose_name='设计师备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('designer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='设计师')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plate_layout', to='orders.order', verbose_name='所属订单')),
            ],
            options={
                'verbose_name': '拼版记录',
                'verbose_name_plural': '拼版记录',
            },
        ),
        migrations.CreateModel(
            name='OrderStatusLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(max_length=30, verbose_name='原状态')),
                ('to_status', models.CharField(max_length=30, verbose_name='新状态')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='orders.order', verbose_name='所属订单')),
            ],
            options={
                'verbose_name': '状态流转日志',
                'verbose_name_plural': '状态流转日志',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('material', models.CharField(choices=[('magnesium', '镁板'), ('copper', '铜板')], max_length=20, verbose_name='材料')),
                ('process_type', models.CharField(choices=[('etching', '腐蚀版'), ('engraving', '雕刻版'), ('resin', '树脂版'), ('film', '菲林')], max_length=20, verbose_name='加工方式')),
                ('thickness', models.CharField(choices=[('1.5', '1.5mm'), ('2.0', '2.0mm'), ('3.0', '3.0mm'), ('4.0', '4.0mm'), ('6.0', '6.0mm')], max_length=10, verbose_name='厚度')),
                ('length_mm', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='长度(mm)')),
                ('width_mm', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='宽度(mm)')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='数量')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='单价(元/cm²)')),
                ('area', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='面积(cm²)')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='小计(元)')),
                ('file', models.FileField(blank=True, null=True, upload_to='order_files/%Y%m/', verbose_name='上传文件')),
                ('file_processed', models.BooleanField(default=False, verbose_name='是否处理文件')),
                ('file_standard_checked', models.BooleanField(default=False, verbose_name='文件符合标准（转曲/矢量）')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='所属订单')),
            ],
            options={
                'verbose_name': '订单明细',
                'verbose_name_plural': '订单明细',
            },
        ),
        migrations.CreateModel(
            name='CommunicationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='沟通内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='orders.order', verbose_name='所属订单')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='发送人')),
            ],
            options={
                'verbose_name': '沟通记录',
                'verbose_name_plural': '沟通记录',
                'ordering': ['created_at'],
            },
        ),
    ]
