# Generated by Django 4.2.30 on 2026-05-17 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_delivery_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='production_completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='生产完成时间'),
        ),
        migrations.AddField(
            model_name='order',
            name='production_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='生产开始时间'),
        ),
    ]
