# Generated by Django 4.2.30 on 2026-05-17 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_production_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='plate_status',
            field=models.CharField(choices=[('none', '未拼版'), ('auto_generated', '已自动拼版-待确认'), ('confirmed', '拼版已确认'), ('rejected', '拼版被驳回')], default='none', max_length=20, verbose_name='拼版状态'),
        ),
    ]
