# Generated by Django 4.2.30 on 2026-05-17 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_plate_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='plate_type',
            field=models.CharField(blank=True, help_text='如:烫金版/压纹版/激凸版/平雕版等', max_length=50, verbose_name='版类'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='red_box_data',
            field=models.TextField(blank=True, help_text='JSON格式: [{x,y,width,height,area}]', verbose_name='红框识别数据'),
        ),
    ]
