# Generated by Django 4.2.30 on 2026-05-17 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0009_alter_orderitem_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('normal', '正常单'), ('remake', '补版单')], default='normal', max_length=20, verbose_name='订单类型'),
        ),
        migrations.AddField(
            model_name='order',
            name='original_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remake_orders', to='orders.order', verbose_name='原订单'),
        ),
        migrations.AddField(
            model_name='order',
            name='remake_initiator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_remake_orders', to=settings.AUTH_USER_MODEL, verbose_name='补版发起人'),
        ),
        migrations.AddField(
            model_name='order',
            name='remake_reason',
            field=models.TextField(blank=True, verbose_name='补版原因'),
        ),
    ]
