# Generated by Django 4.2.30 on 2026-05-20 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_order_type_order_original_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionphoto',
            name='photo_type',
            field=models.CharField(choices=[('front', '成品正面'), ('inspection', '检测结果'), ('express_receipt', '快递单照片'), ('delivery_photo', '派送照片')], max_length=20, verbose_name='照片类型'),
        ),
    ]
