# Generated by Django 4.2.30 on 2026-05-21 01:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customerprofile_is_main_account_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0011_alter_productionphoto_photo_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_settled',
            field=models.BooleanField(default=False, help_text='对账单结清后标记为True，额度释放', verbose_name='是否已结清'),
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sn', models.CharField(blank=True, max_length=30, unique=True, verbose_name='对账单号')),
                ('period_start', models.DateField(verbose_name='账单周期开始')),
                ('period_end', models.DateField(verbose_name='账单周期结束')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='账单总金额')),
                ('status', models.CharField(choices=[('pending', '待对账'), ('confirmed', '已确认'), ('paid', '已付款'), ('settled', '已结清')], default='pending', max_length=20, verbose_name='对账状态')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='客户确认时间')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='客户付款时间')),
                ('settled_at', models.DateTimeField(blank=True, null=True, verbose_name='结清时间')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to=settings.AUTH_USER_MODEL, verbose_name='客户')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='accounts.merchant', verbose_name='所属商家')),
                ('settled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settled_statements', to=settings.AUTH_USER_MODEL, verbose_name='结清操作人')),
            ],
            options={
                'verbose_name': '对账单',
                'verbose_name_plural': '对账单',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='statement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.statement', verbose_name='所属对账单'),
        ),
    ]
