# Generated by Django 4.2.30 on 2026-05-21 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_is_settled_statement_order_statement'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_image_file',
            field=models.BooleanField(default=False, verbose_name='文件是图片文件'),
        ),
    ]
