# Generated by Django 4.2.30 on 2026-05-21 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0014_order_shipped_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionphoto',
            name='photo_type',
            field=models.CharField(choices=[('front', '成品正面'), ('inspection', '检测结果'), ('express_receipt', '快递单照片'), ('delivery_photo', '派送照片'), ('production', '生产实物照片')], max_length=20, verbose_name='照片类型'),
        ),
        migrations.CreateModel(
            name='DeliveryExtension',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_date', models.DateTimeField(blank=True, null=True, verbose_name='原交货时间')),
                ('new_date', models.DateTimeField(blank=True, null=True, verbose_name='新交货时间')),
                ('reason', models.TextField(blank=True, verbose_name='延长原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_delivery_extensions', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_extensions', to='orders.order', verbose_name='所属订单')),
            ],
            options={
                'verbose_name': '交货延期记录',
                'verbose_name_plural': '交货延期记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
