# Generated by Django 4.2.30 on 2026-05-22 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_alter_productionphoto_photo_type_deliveryextension'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking_company',
            field=models.CharField(blank=True, max_length=50, verbose_name='快递公司'),
        ),
    ]
