# Generated by Django 4.2.30 on 2026-05-22 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('merchant_platform', '0002_factoryinventory_factoryequipmentstatus'),
        ('accounts', '0004_customerprofile_is_main_account_and_more'),
        ('orders', '0016_order_tracking_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlateBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(blank=True, max_length=50, verbose_name='产品类型')),
                ('material', models.CharField(blank=True, max_length=50, verbose_name='材质')),
                ('thickness', models.CharField(blank=True, max_length=20, verbose_name='厚度')),
                ('plate_spec_name', models.CharField(blank=True, max_length=50, verbose_name='板材规格')),
                ('plate_width', models.FloatField(default=0, verbose_name='板材宽度(mm)')),
                ('plate_height', models.FloatField(default=0, verbose_name='板材高度(mm)')),
                ('layout_data', models.TextField(blank=True, default='', verbose_name='拼版布局数据')),
                ('layout_image', models.ImageField(blank=True, null=True, upload_to='plate_layouts/%Y%m/', verbose_name='拼版效果图')),
                ('usage_rate', models.FloatField(blank=True, null=True, verbose_name='材料利用率(%)')),
                ('status', models.CharField(choices=[('auto_generated', '系统自动生成'), ('confirmed', '已确认'), ('rejected', '已驳回'), ('in_production', '生产中')], default='auto_generated', max_length=20, verbose_name='状态')),
                ('designer_note', models.TextField(blank=True, verbose_name='设计师备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('designer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designed_plate_batches', to=settings.AUTH_USER_MODEL, verbose_name='设计师')),
                ('factory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plate_batches', to='merchant_platform.factory', verbose_name='生产工厂')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plate_batches', to='accounts.merchant', verbose_name='所属商家')),
            ],
            options={
                'verbose_name': '拼版批次',
                'verbose_name_plural': '拼版批次',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='platelayout',
            options={'verbose_name': '拼版记录(旧)', 'verbose_name_plural': '拼版记录(旧)'},
        ),
        migrations.CreateModel(
            name='PlateBatchItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('x', models.FloatField(default=0, verbose_name='X坐标(mm)')),
                ('y', models.FloatField(default=0, verbose_name='Y坐标(mm)')),
                ('width', models.FloatField(default=0, verbose_name='放置宽度(mm)')),
                ('height', models.FloatField(default=0, verbose_name='放置高度(mm)')),
                ('rotation', models.IntegerField(default=0, help_text='0或90', verbose_name='旋转角度')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plate_batch_items', to='orders.order', verbose_name='所属订单')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plate_batch_items', to='orders.orderitem', verbose_name='订单明细')),
                ('plate_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.platebatch', verbose_name='所属拼版批次')),
            ],
            options={
                'verbose_name': '拼版批次项目',
                'verbose_name_plural': '拼版批次项目',
            },
        ),
        migrations.AddField(
            model_name='orderitem',
            name='plate_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='orders.platebatch', verbose_name='所属拼版批次'),
        ),
    ]
