# Generated by Django 4.2.30 on 2026-05-22 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_platebatch_alter_platelayout_options_platebatchitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platebatch',
            name='production_pdf',
            field=models.FileField(blank=True, null=True, upload_to='plate_layouts/%Y%m/', verbose_name='生产PDF文件'),
        ),
    ]
