# Generated by Django 4.2.30 on 2026-06-02 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_platebatch_production_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='original_file_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='原始文件名'),
        ),
    ]
