# Generated by Django 4.2.30 on 2026-06-04 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0019_orderitem_original_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='plate_file',
            field=models.FileField(blank=True, help_text='工作人员上传的处理后制版文件（PDF/AI）', null=True, upload_to='plate_files/%Y%m/', verbose_name='制版文件'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='plate_file_uploaded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='制版文件上传时间'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='plate_file_uploaded_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type__in': ['merchant_admin', 'merchant_staff']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plate_uploads', to=settings.AUTH_USER_MODEL, verbose_name='制版文件上传人'),
        ),
    ]
