# Generated by Django 4.2.30 on 2026-06-05 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0021_backfill_original_file_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderComplaint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('complaint_type', models.CharField(default='quality', max_length=50, verbose_name='投诉类型')),
                ('description', models.TextField(verbose_name='投诉描述')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='complaints/%Y%m/', verbose_name='投诉图片1')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='complaints/%Y%m/', verbose_name='投诉图片2')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='complaints/%Y%m/', verbose_name='投诉图片3')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('resolved', '已解决'), ('rejected', '已驳回')], default='pending', max_length=20, verbose_name='处理状态')),
                ('merchant_remark', models.TextField(blank=True, verbose_name='商家处理备注')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL, verbose_name='投诉客户')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='orders.order', verbose_name='关联订单')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_complaints', to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
            ],
            options={
                'verbose_name': '订单投诉',
                'verbose_name_plural': '订单投诉',
                'ordering': ['-created_at'],
            },
        ),
    ]
