# Generated by Django 4.2.30 on 2026-06-05 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_ordercomplaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='special_requests',
            field=models.TextField(blank=True, help_text='该规格组的特殊要求', verbose_name='特殊要求备注'),
        ),
    ]
