# Generated by Django 4.2.30 on 2026-06-05 09:44

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_add_item_special_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='scale_ratio',
            field=models.DecimalField(decimal_places=3, default=Decimal('100.000'), help_text='默认100%不缩放，建议99.75%补偿金属加热膨胀', max_digits=6, verbose_name='缩放比例(%)'),
        ),
    ]
