# Generated by Django 4.2.30 on 2026-06-06 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_alter_orderitem_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='preview_image',
            field=models.FileField(blank=True, null=True, upload_to='previews/%Y%m/', verbose_name='预览图'),
        ),
    ]
