# Generated by Django 4.2.30 on 2026-06-06 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_orderitem_preview_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_service_processed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='客服处理时间'),
        ),
        migrations.AddField(
            model_name='order',
            name='factory_downloaded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='工厂下载时间'),
        ),
        migrations.AddField(
            model_name='order',
            name='factory_notified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='工厂通知时间'),
        ),
        migrations.AddField(
            model_name='order',
            name='file_uploaded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='客户上传文件时间'),
        ),
    ]
