# Generated by Django 4.2.30 on 2026-06-10 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_order_customer_service_processed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercomplaint',
            name='complaint_type',
            field=models.CharField(choices=[('file_blur', '糊版'), ('file_broken', '断线'), ('file_type_confusion', '版类混淆'), ('file_scale_missing', '扩缩遗漏'), ('file_thickness_wrong', '厚度错误'), ('file_material_wrong', '材料错误'), ('file_direction_wrong', '方向/镜像错误'), ('file_content_missing', '内容缺失'), ('file_size_wrong', '尺寸错误'), ('file_line_width', '线宽不足'), ('file_color_mode', '颜色模式错误'), ('file_layout_wrong', '拼版错误'), ('file_version_wrong', '版本错误'), ('file_note_missing', '注释遗漏'), ('prod_blur', '糊版（生产）'), ('prod_broken', '断线（生产）'), ('prod_film_issue', '菲林问题'), ('prod_depth_uneven', '深度不均'), ('prod_resin_residual', '树脂残留'), ('prod_surface_scratch', '版面划痕/剐蹭'), ('prod_surface_uneven', '版面不平'), ('prod_oxidation', '版面氧化/生锈'), ('prod_exposure_under', '曝光不足'), ('prod_exposure_over', '曝光过度'), ('prod_edge_chipping', '雕刻崩边'), ('prod_pattern_rough', '图案坡度锯齿'), ('prod_demolding', '去膜不净'), ('prod_cleaning_damage', '清洗损伤'), ('prod_machine_fault', '机器故障'), ('prod_temp_humidity', '温湿度异常'), ('shipping_delay', '发货延迟'), ('shipping_damage', '运输损坏'), ('shipping_lost', '物流丢失'), ('shipping_wrong', '发错货物'), ('other', '其他问题')], default='other', max_length=50, verbose_name='投诉类型'),
        ),
    ]
