# Generated by Django 6.0.6 on 2026-06-22 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0029_alter_ordercomplaint_complaint_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='actual_delivery_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='商户发货时填写的实际运费', max_digits=10, verbose_name='实际运费'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_factory',
            field=models.CharField(blank=True, help_text='guangzhou/nantong', max_length=20, verbose_name='发货工厂'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='顺丰标快预估运费', max_digits=10, verbose_name='预估运费'),
        ),
    ]
