# Generated by Django 6.0.6 on 2026-06-22 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0030_order_actual_delivery_fee_order_delivery_factory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking_last_context',
            field=models.CharField(blank=True, help_text='最新一条物流信息摘要', max_length=200, verbose_name='最新物流节点'),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_last_update',
            field=models.DateTimeField(blank=True, null=True, verbose_name='物流更新时间'),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_status',
            field=models.CharField(blank=True, help_text='缓存最新物流状态：0运输中/1揽收/2疑难/3签收/4退签/5派件/6退回', max_length=20, verbose_name='物流状态'),
        ),
    ]
