# Generated by Django 6.0.6 on 2026-06-22 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0031_order_tracking_last_context_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address_fill_status',
            field=models.CharField(choices=[('not_required', '无需填写'), ('pending', '待填写'), ('filled', '已填写')], default='not_required', help_text='隐私地址模式下客户填写地址的状态', max_length=20, verbose_name='地址填写状态'),
        ),
        migrations.AddField(
            model_name='order',
            name='express_label_image',
            field=models.ImageField(blank=True, help_text='工厂贴好预打印单后拍照上传', null=True, upload_to='express_labels/%Y/%m/', verbose_name='快递单照片'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_private_address',
            field=models.BooleanField(default=False, help_text='客户自行扫码填写地址，系统不保存具体地址', verbose_name='隐私地址发货'),
        ),
    ]
