# Generated by Django 4.2.30 on 2026-05-17 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='pricing_tier',
            field=models.PositiveSmallIntegerField(default=3, verbose_name='价格档位'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='province',
            field=models.CharField(blank=True, max_length=50, verbose_name='所在省份'),
        ),
    ]
