# Generated by Django 4.2.30 on 2026-05-20 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customerprofile_pricing_tier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='custom_prices',
            field=models.TextField(blank=True, default='{}', verbose_name='客户自定义报价'),
        ),
    ]
