# Generated by Django 4.2.30 on 2026-05-20 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customerprofile_custom_prices'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='is_main_account',
            field=models.BooleanField(default=True, verbose_name='是否主账号'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='max_sub_accounts',
            field=models.PositiveIntegerField(default=10, verbose_name='子账号上限'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_accounts', to='accounts.customerprofile', verbose_name='所属主账号'),
        ),
    ]
