# Generated by Django 6.0.6 on 2026-06-15 00:59

import ast
import json
from django.db import migrations, models


def _normalize_permissions(value):
    """将旧 TextField 中的权限数据转换为合法 JSON 字典。"""
    if not value:
        return {}
    if isinstance(value, dict):
        return {k: v for k, v in value.items() if isinstance(v, bool)}
    if isinstance(value, str):
        # 先尝试 JSON
        try:
            parsed = json.loads(value)
            if isinstance(parsed, dict):
                return parsed
        except Exception:
            pass
        # 再尝试 Python 字面量（兼容旧代码中直接保存的 dict repr）
        try:
            parsed = ast.literal_eval(value)
            if isinstance(parsed, dict):
                return parsed
        except Exception:
            pass
    return {}


def normalize_role_permissions(apps, schema_editor):
    """在字段类型变更前，先把所有存量数据清洗为合法 JSON 字符串。"""
    Role = apps.get_model('accounts', 'Role')
    for role in Role.objects.all():
        normalized = _normalize_permissions(role.permissions)
        role.permissions = json.dumps(normalized, ensure_ascii=False)
        role.save(update_fields=['permissions'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customerprofile_is_main_account_and_more'),
    ]

    operations = [
        migrations.RunPython(normalize_role_permissions, noop),
        migrations.AlterField(
            model_name='role',
            name='permissions',
            field=models.JSONField(blank=True, default=dict, verbose_name='权限配置'),
        ),
    ]
