# Generated by Django 4.2.30 on 2026-05-16 22:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='工厂名称')),
                ('address', models.TextField(blank=True, verbose_name='工厂地址')),
                ('contact_person', models.CharField(blank=True, max_length=50, verbose_name='联系人')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factories', to='accounts.merchant', verbose_name='所属商家')),
            ],
            options={
                'verbose_name': '工厂',
                'verbose_name_plural': '工厂',
            },
        ),
    ]
