# Generated by Django 4.2.30 on 2026-05-21 10:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_platform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactoryInventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='分类')),
                ('quantity', models.CharField(blank=True, max_length=50, verbose_name='数量')),
                ('unit', models.CharField(blank=True, max_length=20, verbose_name='单位')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='merchant_platform.factory', verbose_name='所属工厂')),
            ],
            options={
                'verbose_name': '工厂库存',
                'verbose_name_plural': '工厂库存',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='FactoryEquipmentStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status_text', models.CharField(default='一切正常', max_length=200, verbose_name='设备状态')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('factory', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_status', to='merchant_platform.factory', verbose_name='所属工厂')),
            ],
            options={
                'verbose_name': '工厂设备状态',
                'verbose_name_plural': '工厂设备状态',
            },
        ),
    ]
